Revert "Use xcrun python3 for make test/docs if available"
This reverts commit 9bc189ea83cab1e74d78d2f97e4b123ee0a8e13d.

It is failing to compile the cffi module.
    c/_cffi_backend.c:5854:2: error: Apple Arm64 ABI requires ffi_prep_cif_var
    #error Apple Arm64 ABI requires ffi_prep_cif_var
     ^
    1 error generated.
    error: command 'xcrun' failed with exit status 1